# Generated by Django 2.0.6 on 2018-10-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20180930_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='contrasena_aspirante',
            field=models.CharField(max_length=256),
        ),
    ]
