# Generated by Django 2.0.6 on 2018-11-29 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0007_auto_20181007_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='aula',
            fields=[
                ('id_aula', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ciclo',
            fields=[
                ('id_ciclo', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=150)),
                ('correlativo', models.IntegerField()),
                ('unidad_valorativa', models.IntegerField()),
                ('id_ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.ciclo')),
                ('id_materia_pre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Materia')),
                ('id_user_para', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id_programa', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=1024, null=True)),
                ('totalUV', models.IntegerField()),
                ('plan_estudio', models.IntegerField()),
                ('duracion_ciclo', models.IntegerField()),
                ('duracion_anio', models.IntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('total_asignaturas', models.IntegerField()),
                ('nota_minima', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cum_minimo', models.DecimalField(decimal_places=2, max_digits=4)),
                ('caracteristicas', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
