# Generated by Django 2.0.6 on 2018-11-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_aula_ciclo_horario_materia_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='activo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ciclo',
            name='activo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horario',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='activo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programa',
            name='activo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
