# Generated by Django 2.0.6 on 2018-11-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20181129_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
