# Generated by Django 2.0.6 on 2018-11-30 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20181129_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='id_user_para',
        ),
    ]
