# Generated by Django 2.0.6 on 2018-12-17 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_materia_id_programa'),
    ]

    operations = [
        migrations.CreateModel(
            name='grupoTeorico',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('cupo', models.IntegerField()),
                ('activo', models.BooleanField()),
                ('id_aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.aula')),
                ('id_ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.ciclo')),
                ('id_docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Docente')),
                ('id_horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.horario')),
                ('id_materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Materia')),
            ],
        ),
    ]
