# Generated by Django 2.0.6 on 2018-12-17 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_grupoteorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoteorico',
            name='id_programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Programa'),
        ),
    ]
