# Generated by Django 2.0.6 on 2018-12-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_grupoteorico_id_programa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='id_ciclo',
        ),
        migrations.AddField(
            model_name='materia',
            name='ciclo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
