# Generated by Django 2.0.6 on 2018-12-28 00:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_auto_20181218_0318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripcion',
            old_name='dia',
            new_name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='grupoteorico',
            name='numero_grupo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
