# Generated by Django 2.0.6 on 2018-12-28 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_auto_20181227_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoteorico',
            name='numero_grupo',
            field=models.IntegerField(blank=True, null=True, verbose_name=django.db.models.deletion.SET_NULL),
        ),
    ]
