# Generated by Django 2.0.6 on 2018-12-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_auto_20181227_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
    ]
