# Generated by Django 2.0.6 on 2019-01-09 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_auto_20181227_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspirante',
            name='programa',
        ),
        migrations.AddField(
            model_name='aspirante',
            name='id_programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Programa'),
        ),
    ]
