# Generated by Django 2.0.6 on 2019-01-10 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_auto_20190109_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='seleccion',
            fields=[
                ('id_seleccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('id_aspirante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Aspirante')),
                ('id_grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.grupoTeorico')),
            ],
        ),
        migrations.CreateModel(
            name='solventes',
            fields=[
                ('id_solvente', models.AutoField(primary_key=True, serialize=False)),
                ('permiso', models.BooleanField()),
                ('id_aspirante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Aspirante')),
                ('id_inscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.inscripcion')),
            ],
        ),
    ]
