# Generated by Django 2.0.6 on 2019-01-12 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_seleccion_solventes'),
    ]

    operations = [
        migrations.CreateModel(
            name='arancel',
            fields=[
                ('id_arancel', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=1000)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='cuota',
            fields=[
                ('id_cuota', models.AutoField(primary_key=True, serialize=False)),
                ('montoTotal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('descuentoTotal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('verificado', models.BooleanField()),
                ('fecha_verificado', models.DateField()),
                ('numero_recibido', models.CharField(max_length=20)),
                ('codigo_barra', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('descripcion', models.CharField(max_length=1000)),
                ('fecha', models.DateField()),
                ('id_arancel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.arancel')),
            ],
        ),
        migrations.AddField(
            model_name='descuento',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='id_descuento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.descuento'),
        ),
    ]
