# Generated by Django 2.0.6 on 2019-01-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_arancel_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='arancel',
            name='tipo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
