# Generated by Django 2.0.6 on 2019-01-15 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_arancel_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='cancelado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuota',
            name='fecha_recibido',
            field=models.DateField(blank=True, null=True, verbose_name=django.db.models.deletion.SET_NULL),
        ),
        migrations.AddField(
            model_name='cuota',
            name='id_arancel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.arancel'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='codigo_barra',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='descuentoTotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='fecha_verificado',
            field=models.DateField(blank=True, null=True, verbose_name=django.db.models.deletion.SET_NULL),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='montoTotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='numero_recibido',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
