# Generated by Django 2.0.6 on 2019-01-15 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_auto_20190115_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='arancel',
            name='id_descuento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.descuento'),
        ),
    ]
