# Generated by Django 2.0.6 on 2019-01-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0029_arancel_id_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='anio',
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuota',
            name='nombre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
