# Generated by Django 2.0.6 on 2019-01-15 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_auto_20190115_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='id_estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Aspirante'),
        ),
    ]
